Primitives: bitwise/shift/division operators on both the spec side and the
Core side, struct values, sizeof, pointer builtins (prov_eq, has_alloc_id),
and good<ct> via CN's own value-check expansion.

Cross-checked against `cn verify`: every function in both files passes in
both tools.

  $ soteria-cn verify prim.c
  Verifying function bits...
  Successfully verified bits
  Verifying function shift3...
  Successfully verified shift3
  Verifying function half...
  Successfully verified half
  Verifying function first_coord...
  Successfully verified first_coord
  Verifying function int_size...
  Successfully verified int_size
  Verifying function prov...
  Successfully verified prov
  $ soteria-cn verify good.c
  Verifying function good_ok...
  Successfully verified good_ok
  Verifying function good_bool...
  Successfully verified good_bool
